# Generated by Django 3.2.20 on 2025-03-27 10:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, choices=[('hnew', 'Home | heading 1'), ('hneww', 'Home | Heading 2'), ('hnewww', 'Home | Heading 3'), ('Programme1', 'Home | Programme1'), ('Programme2', 'Home | Programme2'), ('Programme3', 'Home | Programme3'), ('about_us', 'Home | About Us'), ('mission', 'Home | Our Mission'), ('vision', 'Home | Our Vision'), ('Volunteer', 'Home | Volunteer'), ('footer', 'Home | Footer'), ('aboutUs', 'About Us | About Us'), ('our_Programs', 'Programs | Goddess Care Initiative'), ('reach', 'Programs | Our Reach '), ('team1', 'Our Team | Kelly'), ('team2', 'Our Team | Elsie'), ('team3', 'Our Team | Loise')], max_length=100, null=True, unique=True)),
                ('heading', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(default='Edit your Bio!')),
                ('website', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
