# Generated by Django 3.2.20 on 2025-03-27 12:41

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='gallery',
            name='multiple_images',
            field=pyuploadcare.dj.models.FileGroupField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='single_image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='upload_type',
            field=models.CharField(choices=[('single', 'Single Image'), ('multiple', 'Multiple Images')], default='single', max_length=10),
        ),
    ]
