# Generated by Django 3.2.20 on 2025-03-27 12:57

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250327_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='multiple_images',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='single_image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='upload_type',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=pyuploadcare.dj.models.FileGroupField(blank=True, null=True),
        ),
    ]
